// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1ActivateVanitySubdomainConfigRequest struct {
	// Project ref
	Ref                 string                     `pathParam:"style=simple,explode=false,name=ref"`
	VanitySubdomainBody shared.VanitySubdomainBody `request:"mediaType=application/json"`
}

func (o *V1ActivateVanitySubdomainConfigRequest) GetRef() string {
	if o == nil {
		return ""
	}
	return o.Ref
}

func (o *V1ActivateVanitySubdomainConfigRequest) GetVanitySubdomainBody() shared.VanitySubdomainBody {
	if o == nil {
		return shared.VanitySubdomainBody{}
	}
	return o.VanitySubdomainBody
}

type V1ActivateVanitySubdomainConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                     *http.Response
	ActivateVanitySubdomainResponse *shared.ActivateVanitySubdomainResponse
}

func (o *V1ActivateVanitySubdomainConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1ActivateVanitySubdomainConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1ActivateVanitySubdomainConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1ActivateVanitySubdomainConfigResponse) GetActivateVanitySubdomainResponse() *shared.ActivateVanitySubdomainResponse {
	if o == nil {
		return nil
	}
	return o.ActivateVanitySubdomainResponse
}
