// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1CreateASsoProviderRequest struct {
	// Project ref
	Ref                string                    `pathParam:"style=simple,explode=false,name=ref"`
	CreateProviderBody shared.CreateProviderBody `request:"mediaType=application/json"`
}

func (o *V1CreateASsoProviderRequest) GetRef() string {
	if o == nil {
		return ""
	}
	return o.Ref
}

func (o *V1CreateASsoProviderRequest) GetCreateProviderBody() shared.CreateProviderBody {
	if o == nil {
		return shared.CreateProviderBody{}
	}
	return o.CreateProviderBody
}

type V1CreateASsoProviderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse            *http.Response
	CreateProviderResponse *shared.CreateProviderResponse
}

func (o *V1CreateASsoProviderResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1CreateASsoProviderResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1CreateASsoProviderResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1CreateASsoProviderResponse) GetCreateProviderResponse() *shared.CreateProviderResponse {
	if o == nil {
		return nil
	}
	return o.CreateProviderResponse
}
