// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/internal/utils"
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1GenerateTypescriptTypesRequest struct {
	IncludedSchemas *string `default:"public" queryParam:"style=form,explode=true,name=included_schemas"`
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

func (v V1GenerateTypescriptTypesRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(v, "", false)
}

func (v *V1GenerateTypescriptTypesRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &v, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *V1GenerateTypescriptTypesRequest) GetIncludedSchemas() *string {
	if o == nil {
		return nil
	}
	return o.IncludedSchemas
}

func (o *V1GenerateTypescriptTypesRequest) GetRef() string {
	if o == nil {
		return ""
	}
	return o.Ref
}

type V1GenerateTypescriptTypesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse        *http.Response
	TypescriptResponse *shared.TypescriptResponse
}

func (o *V1GenerateTypescriptTypesResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1GenerateTypescriptTypesResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1GenerateTypescriptTypesResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1GenerateTypescriptTypesResponse) GetTypescriptResponse() *shared.TypescriptResponse {
	if o == nil {
		return nil
	}
	return o.TypescriptResponse
}
