// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"net/http"
)

type V1GetAFunctionBodyRequest struct {
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
	// Function slug
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *V1GetAFunctionBodyRequest) GetRef() string {
	if o == nil {
		return ""
	}
	return o.Ref
}

func (o *V1GetAFunctionBodyRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type V1GetAFunctionBodyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *V1GetAFunctionBodyResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1GetAFunctionBodyResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1GetAFunctionBodyResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
