// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1GetAFunctionRequest struct {
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
	// Function slug
	FunctionSlug string `pathParam:"style=simple,explode=false,name=function_slug"`
}

func (o *V1GetAFunctionRequest) GetRef() string {
	if o == nil {
		return ""
	}
	return o.Ref
}

func (o *V1GetAFunctionRequest) GetFunctionSlug() string {
	if o == nil {
		return ""
	}
	return o.FunctionSlug
}

type V1GetAFunctionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse          *http.Response
	FunctionSlugResponse *shared.FunctionSlugResponse
}

func (o *V1GetAFunctionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1GetAFunctionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1GetAFunctionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1GetAFunctionResponse) GetFunctionSlugResponse() *shared.FunctionSlugResponse {
	if o == nil {
		return nil
	}
	return o.FunctionSlugResponse
}
