// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1ListOrganizationMembersRequest struct {
	Slug string `pathParam:"style=simple,explode=false,name=slug"`
}

func (o *V1ListOrganizationMembersRequest) GetSlug() string {
	if o == nil {
		return ""
	}
	return o.Slug
}

type V1ListOrganizationMembersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse                   *http.Response
	V1OrganizationMemberResponses []shared.V1OrganizationMemberResponse
}

func (o *V1ListOrganizationMembersResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1ListOrganizationMembersResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1ListOrganizationMembersResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1ListOrganizationMembersResponse) GetV1OrganizationMemberResponses() []shared.V1OrganizationMemberResponse {
	if o == nil {
		return nil
	}
	return o.V1OrganizationMemberResponses
}
