// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1ListAllSecretsRequest struct {
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

func (o *V1ListAllSecretsRequest) GetRef() string {
	if o == nil {
		return ""
	}
	return o.Ref
}

type V1ListAllSecretsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse     *http.Response
	SecretResponses []shared.SecretResponse
}

func (o *V1ListAllSecretsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1ListAllSecretsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1ListAllSecretsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1ListAllSecretsResponse) GetSecretResponses() []shared.SecretResponse {
	if o == nil {
		return nil
	}
	return o.SecretResponses
}
