// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1ResetABranchRequest struct {
	// Branch ID
	BranchID string `pathParam:"style=simple,explode=false,name=branch_id"`
}

func (o *V1ResetABranchRequest) GetBranchID() string {
	if o == nil {
		return ""
	}
	return o.BranchID
}

type V1ResetABranchResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse         *http.Response
	BranchResetResponse *shared.BranchResetResponse
}

func (o *V1ResetABranchResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1ResetABranchResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1ResetABranchResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1ResetABranchResponse) GetBranchResetResponse() *shared.BranchResetResponse {
	if o == nil {
		return nil
	}
	return o.BranchResetResponse
}
