// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/shared"
	"net/http"
)

type V1UpdatePgsodiumConfigRequest struct {
	// Project ref
	Ref                      string                          `pathParam:"style=simple,explode=false,name=ref"`
	UpdatePgsodiumConfigBody shared.UpdatePgsodiumConfigBody `request:"mediaType=application/json"`
}

func (o *V1UpdatePgsodiumConfigRequest) GetRef() string {
	if o == nil {
		return ""
	}
	return o.Ref
}

func (o *V1UpdatePgsodiumConfigRequest) GetUpdatePgsodiumConfigBody() shared.UpdatePgsodiumConfigBody {
	if o == nil {
		return shared.UpdatePgsodiumConfigBody{}
	}
	return o.UpdatePgsodiumConfigBody
}

type V1UpdatePgsodiumConfigResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse            *http.Response
	PgsodiumConfigResponse *shared.PgsodiumConfigResponse
}

func (o *V1UpdatePgsodiumConfigResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *V1UpdatePgsodiumConfigResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *V1UpdatePgsodiumConfigResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *V1UpdatePgsodiumConfigResponse) GetPgsodiumConfigResponse() *shared.PgsodiumConfigResponse {
	if o == nil {
		return nil
	}
	return o.PgsodiumConfigResponse
}
