// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type PostgresConfigResponseSessionReplicationRoleEnum string

const (
	PostgresConfigResponseSessionReplicationRoleEnumOrigin  PostgresConfigResponseSessionReplicationRoleEnum = "origin"
	PostgresConfigResponseSessionReplicationRoleEnumReplica PostgresConfigResponseSessionReplicationRoleEnum = "replica"
	PostgresConfigResponseSessionReplicationRoleEnumLocal   PostgresConfigResponseSessionReplicationRoleEnum = "local"
)

func (e PostgresConfigResponseSessionReplicationRoleEnum) ToPointer() *PostgresConfigResponseSessionReplicationRoleEnum {
	return &e
}

func (e *PostgresConfigResponseSessionReplicationRoleEnum) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "origin":
		fallthrough
	case "replica":
		fallthrough
	case "local":
		*e = PostgresConfigResponseSessionReplicationRoleEnum(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostgresConfigResponseSessionReplicationRoleEnum: %v", v)
	}
}

type PostgresConfigResponse struct {
	EffectiveCacheSize            int64                                            `json:"effective_cache_size"`
	MaintenanceWorkMem            int64                                            `json:"maintenance_work_mem"`
	MaxConnections                int64                                            `json:"max_connections"`
	MaxParallelMaintenanceWorkers int64                                            `json:"max_parallel_maintenance_workers"`
	MaxParallelWorkers            int64                                            `json:"max_parallel_workers"`
	MaxParallelWorkersPerGather   int64                                            `json:"max_parallel_workers_per_gather"`
	MaxWorkerProcesses            int64                                            `json:"max_worker_processes"`
	SessionReplicationRole        PostgresConfigResponseSessionReplicationRoleEnum `json:"session_replication_role"`
	SharedBuffers                 int64                                            `json:"shared_buffers"`
	StatementTimeout              int64                                            `json:"statement_timeout"`
	WorkMem                       int64                                            `json:"work_mem"`
}
