// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SamlDescriptor struct {
	AttributeMapping *AttributeMapping `json:"attribute_mapping,omitempty"`
	EntityID         string            `json:"entity_id"`
	ID               string            `json:"id"`
	MetadataURL      *string           `json:"metadata_url,omitempty"`
	MetadataXML      *string           `json:"metadata_xml,omitempty"`
}
