// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type APIKeyResponseType string

const (
	APIKeyResponseTypePublishable APIKeyResponseType = "publishable"
	APIKeyResponseTypeSecret      APIKeyResponseType = "secret"
	APIKeyResponseTypeLegacy      APIKeyResponseType = "legacy"
)

func (e APIKeyResponseType) ToPointer() *APIKeyResponseType {
	return &e
}
func (e *APIKeyResponseType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "publishable":
		fallthrough
	case "secret":
		fallthrough
	case "legacy":
		*e = APIKeyResponseType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for APIKeyResponseType: %v", v)
	}
}

type SecretJwtTemplate struct {
	Role string `json:"role"`
}

func (o *SecretJwtTemplate) GetRole() string {
	if o == nil {
		return ""
	}
	return o.Role
}

type APIKeyResponse struct {
	Type              *APIKeyResponseType `json:"type,omitempty"`
	Name              string              `json:"name"`
	APIKey            string              `json:"api_key"`
	ID                *string             `json:"id,omitempty"`
	Prefix            *string             `json:"prefix,omitempty"`
	Description       *string             `json:"description,omitempty"`
	Hash              *string             `json:"hash,omitempty"`
	SecretJwtTemplate *SecretJwtTemplate  `json:"secret_jwt_template,omitempty"`
	InsertedAt        *string             `json:"inserted_at,omitempty"`
	UpdatedAt         *string             `json:"updated_at,omitempty"`
}

func (o *APIKeyResponse) GetType() *APIKeyResponseType {
	if o == nil {
		return nil
	}
	return o.Type
}

func (o *APIKeyResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *APIKeyResponse) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

func (o *APIKeyResponse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *APIKeyResponse) GetPrefix() *string {
	if o == nil {
		return nil
	}
	return o.Prefix
}

func (o *APIKeyResponse) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *APIKeyResponse) GetHash() *string {
	if o == nil {
		return nil
	}
	return o.Hash
}

func (o *APIKeyResponse) GetSecretJwtTemplate() *SecretJwtTemplate {
	if o == nil {
		return nil
	}
	return o.SecretJwtTemplate
}

func (o *APIKeyResponse) GetInsertedAt() *string {
	if o == nil {
		return nil
	}
	return o.InsertedAt
}

func (o *APIKeyResponse) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
