// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type BillingPlanID string

const (
	BillingPlanIDFree       BillingPlanID = "free"
	BillingPlanIDPro        BillingPlanID = "pro"
	BillingPlanIDTeam       BillingPlanID = "team"
	BillingPlanIDEnterprise BillingPlanID = "enterprise"
)

func (e BillingPlanID) ToPointer() *BillingPlanID {
	return &e
}
func (e *BillingPlanID) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "free":
		fallthrough
	case "pro":
		fallthrough
	case "team":
		fallthrough
	case "enterprise":
		*e = BillingPlanID(v)
		return nil
	default:
		return fmt.Errorf("invalid value for BillingPlanID: %v", v)
	}
}
