// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type BranchDeleteResponse struct {
	Message string `json:"message"`
}

func (o *BranchDeleteResponse) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
