// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetProviderResponse struct {
	ID        string          `json:"id"`
	Saml      *SamlDescriptor `json:"saml,omitempty"`
	Domains   []Domain        `json:"domains,omitempty"`
	CreatedAt *string         `json:"created_at,omitempty"`
	UpdatedAt *string         `json:"updated_at,omitempty"`
}

func (o *GetProviderResponse) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *GetProviderResponse) GetSaml() *SamlDescriptor {
	if o == nil {
		return nil
	}
	return o.Saml
}

func (o *GetProviderResponse) GetDomains() []Domain {
	if o == nil {
		return nil
	}
	return o.Domains
}

func (o *GetProviderResponse) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *GetProviderResponse) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}
