// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListProvidersResponse struct {
	Items []Provider `json:"items"`
}

func (o *ListProvidersResponse) GetItems() []Provider {
	if o == nil {
		return []Provider{}
	}
	return o.Items
}
