// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NetworkBanResponse struct {
	BannedIpv4Addresses []string `json:"banned_ipv4_addresses"`
}

func (o *NetworkBanResponse) GetBannedIpv4Addresses() []string {
	if o == nil {
		return []string{}
	}
	return o.BannedIpv4Addresses
}
