// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// PostgresEngine - Postgres engine version. If not provided, the latest version will be used.
type PostgresEngine string

const (
	PostgresEngineFifteen PostgresEngine = "15"
)

func (e PostgresEngine) ToPointer() *PostgresEngine {
	return &e
}
func (e *PostgresEngine) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "15":
		*e = PostgresEngine(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostgresEngine: %v", v)
	}
}
