// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ProjectVersion struct {
	// Postgres engine version. If not provided, the latest version will be used.
	PostgresVersion PostgresEngine `json:"postgres_version"`
	ReleaseChannel  ReleaseChannel `json:"release_channel"`
	AppVersion      string         `json:"app_version"`
}

func (o *ProjectVersion) GetPostgresVersion() PostgresEngine {
	if o == nil {
		return PostgresEngine("")
	}
	return o.PostgresVersion
}

func (o *ProjectVersion) GetReleaseChannel() ReleaseChannel {
	if o == nil {
		return ReleaseChannel("")
	}
	return o.ReleaseChannel
}

func (o *ProjectVersion) GetAppVersion() string {
	if o == nil {
		return ""
	}
	return o.AppVersion
}
