// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RemoveReadReplicaBody struct {
	DatabaseIdentifier string `json:"database_identifier"`
}

func (o *RemoveReadReplicaBody) GetDatabaseIdentifier() string {
	if o == nil {
		return ""
	}
	return o.DatabaseIdentifier
}
