// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SecretResponse struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

func (o *SecretResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *SecretResponse) GetValue() string {
	if o == nil {
		return ""
	}
	return o.Value
}
