// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type SubdomainAvailabilityResponse struct {
	Available bool `json:"available"`
}

func (o *SubdomainAvailabilityResponse) GetAvailable() bool {
	if o == nil {
		return false
	}
	return o.Available
}
