// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateSupavisorConfigBody struct {
	DefaultPoolSize *int64 `json:"default_pool_size,omitempty"`
}

func (o *UpdateSupavisorConfigBody) GetDefaultPoolSize() *int64 {
	if o == nil {
		return nil
	}
	return o.DefaultPoolSize
}
