// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateAPIKeyBodySecretJwtTemplate struct {
	Role string `json:"role"`
}

func (o *UpdateAPIKeyBodySecretJwtTemplate) GetRole() string {
	if o == nil {
		return ""
	}
	return o.Role
}

type UpdateAPIKeyBody struct {
	Description       *string                            `json:"description,omitempty"`
	SecretJwtTemplate *UpdateAPIKeyBodySecretJwtTemplate `json:"secret_jwt_template,omitempty"`
}

func (o *UpdateAPIKeyBody) GetDescription() *string {
	if o == nil {
		return nil
	}
	return o.Description
}

func (o *UpdateAPIKeyBody) GetSecretJwtTemplate() *UpdateAPIKeyBodySecretJwtTemplate {
	if o == nil {
		return nil
	}
	return o.SecretJwtTemplate
}
