// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V1BackupsResponse struct {
	Region             string           `json:"region"`
	WalgEnabled        bool             `json:"walg_enabled"`
	PitrEnabled        bool             `json:"pitr_enabled"`
	Backups            []V1Backup       `json:"backups"`
	PhysicalBackupData V1PhysicalBackup `json:"physical_backup_data"`
}

func (o *V1BackupsResponse) GetRegion() string {
	if o == nil {
		return ""
	}
	return o.Region
}

func (o *V1BackupsResponse) GetWalgEnabled() bool {
	if o == nil {
		return false
	}
	return o.WalgEnabled
}

func (o *V1BackupsResponse) GetPitrEnabled() bool {
	if o == nil {
		return false
	}
	return o.PitrEnabled
}

func (o *V1BackupsResponse) GetBackups() []V1Backup {
	if o == nil {
		return []V1Backup{}
	}
	return o.Backups
}

func (o *V1BackupsResponse) GetPhysicalBackupData() V1PhysicalBackup {
	if o == nil {
		return V1PhysicalBackup{}
	}
	return o.PhysicalBackupData
}
