// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V1RestorePitrBody struct {
	RecoveryTimeTargetUnix int64 `json:"recovery_time_target_unix"`
}

func (o *V1RestorePitrBody) GetRecoveryTimeTargetUnix() int64 {
	if o == nil {
		return 0
	}
	return o.RecoveryTimeTargetUnix
}
