// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type V1RunQueryBody struct {
	Query string `json:"query"`
}

func (o *V1RunQueryBody) GetQuery() string {
	if o == nil {
		return ""
	}
	return o.Query
}
