/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1CreateAFunctionRequest = {
  /**
   * Project ref
   */
  ref: string;
  slug?: string | undefined;
  name?: string | undefined;
  verifyJwt?: boolean | undefined;
  importMap?: boolean | undefined;
  entrypointPath?: string | undefined;
  importMapPath?: string | undefined;
  computeMultiplier?: number | undefined;
  v1CreateFunctionBody: components.V1CreateFunctionBody;
};

/** @internal */
export const V1CreateAFunctionRequest$inboundSchema: z.ZodType<
  V1CreateAFunctionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  slug: z.string().optional(),
  name: z.string().optional(),
  verify_jwt: z.boolean().optional(),
  import_map: z.boolean().optional(),
  entrypoint_path: z.string().optional(),
  import_map_path: z.string().optional(),
  compute_multiplier: z.number().optional(),
  V1CreateFunctionBody: components.V1CreateFunctionBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "verify_jwt": "verifyJwt",
    "import_map": "importMap",
    "entrypoint_path": "entrypointPath",
    "import_map_path": "importMapPath",
    "compute_multiplier": "computeMultiplier",
    "V1CreateFunctionBody": "v1CreateFunctionBody",
  });
});

/** @internal */
export type V1CreateAFunctionRequest$Outbound = {
  ref: string;
  slug?: string | undefined;
  name?: string | undefined;
  verify_jwt?: boolean | undefined;
  import_map?: boolean | undefined;
  entrypoint_path?: string | undefined;
  import_map_path?: string | undefined;
  compute_multiplier?: number | undefined;
  V1CreateFunctionBody: components.V1CreateFunctionBody$Outbound;
};

/** @internal */
export const V1CreateAFunctionRequest$outboundSchema: z.ZodType<
  V1CreateAFunctionRequest$Outbound,
  z.ZodTypeDef,
  V1CreateAFunctionRequest
> = z.object({
  ref: z.string(),
  slug: z.string().optional(),
  name: z.string().optional(),
  verifyJwt: z.boolean().optional(),
  importMap: z.boolean().optional(),
  entrypointPath: z.string().optional(),
  importMapPath: z.string().optional(),
  computeMultiplier: z.number().optional(),
  v1CreateFunctionBody: components.V1CreateFunctionBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    verifyJwt: "verify_jwt",
    importMap: "import_map",
    entrypointPath: "entrypoint_path",
    importMapPath: "import_map_path",
    computeMultiplier: "compute_multiplier",
    v1CreateFunctionBody: "V1CreateFunctionBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1CreateAFunctionRequest$ {
  /** @deprecated use `V1CreateAFunctionRequest$inboundSchema` instead. */
  export const inboundSchema = V1CreateAFunctionRequest$inboundSchema;
  /** @deprecated use `V1CreateAFunctionRequest$outboundSchema` instead. */
  export const outboundSchema = V1CreateAFunctionRequest$outboundSchema;
  /** @deprecated use `V1CreateAFunctionRequest$Outbound` instead. */
  export type Outbound = V1CreateAFunctionRequest$Outbound;
}

export function v1CreateAFunctionRequestToJSON(
  v1CreateAFunctionRequest: V1CreateAFunctionRequest,
): string {
  return JSON.stringify(
    V1CreateAFunctionRequest$outboundSchema.parse(v1CreateAFunctionRequest),
  );
}

export function v1CreateAFunctionRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1CreateAFunctionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1CreateAFunctionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1CreateAFunctionRequest' from JSON`,
  );
}
