/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1DeleteAFunctionRequest = {
  /**
   * Project ref
   */
  ref: string;
  /**
   * Function slug
   */
  slug: string;
};

/** @internal */
export const V1DeleteAFunctionRequest$inboundSchema: z.ZodType<
  V1DeleteAFunctionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  slug: z.string(),
});

/** @internal */
export type V1DeleteAFunctionRequest$Outbound = {
  ref: string;
  slug: string;
};

/** @internal */
export const V1DeleteAFunctionRequest$outboundSchema: z.ZodType<
  V1DeleteAFunctionRequest$Outbound,
  z.ZodTypeDef,
  V1DeleteAFunctionRequest
> = z.object({
  ref: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1DeleteAFunctionRequest$ {
  /** @deprecated use `V1DeleteAFunctionRequest$inboundSchema` instead. */
  export const inboundSchema = V1DeleteAFunctionRequest$inboundSchema;
  /** @deprecated use `V1DeleteAFunctionRequest$outboundSchema` instead. */
  export const outboundSchema = V1DeleteAFunctionRequest$outboundSchema;
  /** @deprecated use `V1DeleteAFunctionRequest$Outbound` instead. */
  export type Outbound = V1DeleteAFunctionRequest$Outbound;
}

export function v1DeleteAFunctionRequestToJSON(
  v1DeleteAFunctionRequest: V1DeleteAFunctionRequest,
): string {
  return JSON.stringify(
    V1DeleteAFunctionRequest$outboundSchema.parse(v1DeleteAFunctionRequest),
  );
}

export function v1DeleteAFunctionRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1DeleteAFunctionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1DeleteAFunctionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1DeleteAFunctionRequest' from JSON`,
  );
}
