/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1DeleteNetworkBansRequest = {
  /**
   * Project ref
   */
  ref: string;
  removeNetworkBanRequest: components.RemoveNetworkBanRequest;
};

/** @internal */
export const V1DeleteNetworkBansRequest$inboundSchema: z.ZodType<
  V1DeleteNetworkBansRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  RemoveNetworkBanRequest: components.RemoveNetworkBanRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "RemoveNetworkBanRequest": "removeNetworkBanRequest",
  });
});

/** @internal */
export type V1DeleteNetworkBansRequest$Outbound = {
  ref: string;
  RemoveNetworkBanRequest: components.RemoveNetworkBanRequest$Outbound;
};

/** @internal */
export const V1DeleteNetworkBansRequest$outboundSchema: z.ZodType<
  V1DeleteNetworkBansRequest$Outbound,
  z.ZodTypeDef,
  V1DeleteNetworkBansRequest
> = z.object({
  ref: z.string(),
  removeNetworkBanRequest: components.RemoveNetworkBanRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    removeNetworkBanRequest: "RemoveNetworkBanRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1DeleteNetworkBansRequest$ {
  /** @deprecated use `V1DeleteNetworkBansRequest$inboundSchema` instead. */
  export const inboundSchema = V1DeleteNetworkBansRequest$inboundSchema;
  /** @deprecated use `V1DeleteNetworkBansRequest$outboundSchema` instead. */
  export const outboundSchema = V1DeleteNetworkBansRequest$outboundSchema;
  /** @deprecated use `V1DeleteNetworkBansRequest$Outbound` instead. */
  export type Outbound = V1DeleteNetworkBansRequest$Outbound;
}

export function v1DeleteNetworkBansRequestToJSON(
  v1DeleteNetworkBansRequest: V1DeleteNetworkBansRequest,
): string {
  return JSON.stringify(
    V1DeleteNetworkBansRequest$outboundSchema.parse(v1DeleteNetworkBansRequest),
  );
}

export function v1DeleteNetworkBansRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1DeleteNetworkBansRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1DeleteNetworkBansRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1DeleteNetworkBansRequest' from JSON`,
  );
}
