/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1DeleteAProjectRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1DeleteAProjectRequest$inboundSchema: z.ZodType<
  V1DeleteAProjectRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1DeleteAProjectRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1DeleteAProjectRequest$outboundSchema: z.ZodType<
  V1DeleteAProjectRequest$Outbound,
  z.ZodTypeDef,
  V1DeleteAProjectRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1DeleteAProjectRequest$ {
  /** @deprecated use `V1DeleteAProjectRequest$inboundSchema` instead. */
  export const inboundSchema = V1DeleteAProjectRequest$inboundSchema;
  /** @deprecated use `V1DeleteAProjectRequest$outboundSchema` instead. */
  export const outboundSchema = V1DeleteAProjectRequest$outboundSchema;
  /** @deprecated use `V1DeleteAProjectRequest$Outbound` instead. */
  export type Outbound = V1DeleteAProjectRequest$Outbound;
}

export function v1DeleteAProjectRequestToJSON(
  v1DeleteAProjectRequest: V1DeleteAProjectRequest,
): string {
  return JSON.stringify(
    V1DeleteAProjectRequest$outboundSchema.parse(v1DeleteAProjectRequest),
  );
}

export function v1DeleteAProjectRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1DeleteAProjectRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1DeleteAProjectRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1DeleteAProjectRequest' from JSON`,
  );
}
