/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1DeactivateVanitySubdomainConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1DeactivateVanitySubdomainConfigRequest$inboundSchema: z.ZodType<
  V1DeactivateVanitySubdomainConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1DeactivateVanitySubdomainConfigRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1DeactivateVanitySubdomainConfigRequest$outboundSchema: z.ZodType<
  V1DeactivateVanitySubdomainConfigRequest$Outbound,
  z.ZodTypeDef,
  V1DeactivateVanitySubdomainConfigRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1DeactivateVanitySubdomainConfigRequest$ {
  /** @deprecated use `V1DeactivateVanitySubdomainConfigRequest$inboundSchema` instead. */
  export const inboundSchema =
    V1DeactivateVanitySubdomainConfigRequest$inboundSchema;
  /** @deprecated use `V1DeactivateVanitySubdomainConfigRequest$outboundSchema` instead. */
  export const outboundSchema =
    V1DeactivateVanitySubdomainConfigRequest$outboundSchema;
  /** @deprecated use `V1DeactivateVanitySubdomainConfigRequest$Outbound` instead. */
  export type Outbound = V1DeactivateVanitySubdomainConfigRequest$Outbound;
}

export function v1DeactivateVanitySubdomainConfigRequestToJSON(
  v1DeactivateVanitySubdomainConfigRequest:
    V1DeactivateVanitySubdomainConfigRequest,
): string {
  return JSON.stringify(
    V1DeactivateVanitySubdomainConfigRequest$outboundSchema.parse(
      v1DeactivateVanitySubdomainConfigRequest,
    ),
  );
}

export function v1DeactivateVanitySubdomainConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<
  V1DeactivateVanitySubdomainConfigRequest,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      V1DeactivateVanitySubdomainConfigRequest$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'V1DeactivateVanitySubdomainConfigRequest' from JSON`,
  );
}
