/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1DeleteHostnameConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1DeleteHostnameConfigRequest$inboundSchema: z.ZodType<
  V1DeleteHostnameConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1DeleteHostnameConfigRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1DeleteHostnameConfigRequest$outboundSchema: z.ZodType<
  V1DeleteHostnameConfigRequest$Outbound,
  z.ZodTypeDef,
  V1DeleteHostnameConfigRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1DeleteHostnameConfigRequest$ {
  /** @deprecated use `V1DeleteHostnameConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V1DeleteHostnameConfigRequest$inboundSchema;
  /** @deprecated use `V1DeleteHostnameConfigRequest$outboundSchema` instead. */
  export const outboundSchema = V1DeleteHostnameConfigRequest$outboundSchema;
  /** @deprecated use `V1DeleteHostnameConfigRequest$Outbound` instead. */
  export type Outbound = V1DeleteHostnameConfigRequest$Outbound;
}

export function v1DeleteHostnameConfigRequestToJSON(
  v1DeleteHostnameConfigRequest: V1DeleteHostnameConfigRequest,
): string {
  return JSON.stringify(
    V1DeleteHostnameConfigRequest$outboundSchema.parse(
      v1DeleteHostnameConfigRequest,
    ),
  );
}

export function v1DeleteHostnameConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1DeleteHostnameConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1DeleteHostnameConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1DeleteHostnameConfigRequest' from JSON`,
  );
}
