/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1GetReadonlyModeStatusRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1GetReadonlyModeStatusRequest$inboundSchema: z.ZodType<
  V1GetReadonlyModeStatusRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1GetReadonlyModeStatusRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1GetReadonlyModeStatusRequest$outboundSchema: z.ZodType<
  V1GetReadonlyModeStatusRequest$Outbound,
  z.ZodTypeDef,
  V1GetReadonlyModeStatusRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1GetReadonlyModeStatusRequest$ {
  /** @deprecated use `V1GetReadonlyModeStatusRequest$inboundSchema` instead. */
  export const inboundSchema = V1GetReadonlyModeStatusRequest$inboundSchema;
  /** @deprecated use `V1GetReadonlyModeStatusRequest$outboundSchema` instead. */
  export const outboundSchema = V1GetReadonlyModeStatusRequest$outboundSchema;
  /** @deprecated use `V1GetReadonlyModeStatusRequest$Outbound` instead. */
  export type Outbound = V1GetReadonlyModeStatusRequest$Outbound;
}

export function v1GetReadonlyModeStatusRequestToJSON(
  v1GetReadonlyModeStatusRequest: V1GetReadonlyModeStatusRequest,
): string {
  return JSON.stringify(
    V1GetReadonlyModeStatusRequest$outboundSchema.parse(
      v1GetReadonlyModeStatusRequest,
    ),
  );
}

export function v1GetReadonlyModeStatusRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1GetReadonlyModeStatusRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1GetReadonlyModeStatusRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1GetReadonlyModeStatusRequest' from JSON`,
  );
}
