/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1GetPostgrestServiceConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1GetPostgrestServiceConfigRequest$inboundSchema: z.ZodType<
  V1GetPostgrestServiceConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1GetPostgrestServiceConfigRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1GetPostgrestServiceConfigRequest$outboundSchema: z.ZodType<
  V1GetPostgrestServiceConfigRequest$Outbound,
  z.ZodTypeDef,
  V1GetPostgrestServiceConfigRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1GetPostgrestServiceConfigRequest$ {
  /** @deprecated use `V1GetPostgrestServiceConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V1GetPostgrestServiceConfigRequest$inboundSchema;
  /** @deprecated use `V1GetPostgrestServiceConfigRequest$outboundSchema` instead. */
  export const outboundSchema =
    V1GetPostgrestServiceConfigRequest$outboundSchema;
  /** @deprecated use `V1GetPostgrestServiceConfigRequest$Outbound` instead. */
  export type Outbound = V1GetPostgrestServiceConfigRequest$Outbound;
}

export function v1GetPostgrestServiceConfigRequestToJSON(
  v1GetPostgrestServiceConfigRequest: V1GetPostgrestServiceConfigRequest,
): string {
  return JSON.stringify(
    V1GetPostgrestServiceConfigRequest$outboundSchema.parse(
      v1GetPostgrestServiceConfigRequest,
    ),
  );
}

export function v1GetPostgrestServiceConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1GetPostgrestServiceConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1GetPostgrestServiceConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1GetPostgrestServiceConfigRequest' from JSON`,
  );
}
