/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1GetProjectPgbouncerConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1GetProjectPgbouncerConfigRequest$inboundSchema: z.ZodType<
  V1GetProjectPgbouncerConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1GetProjectPgbouncerConfigRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1GetProjectPgbouncerConfigRequest$outboundSchema: z.ZodType<
  V1GetProjectPgbouncerConfigRequest$Outbound,
  z.ZodTypeDef,
  V1GetProjectPgbouncerConfigRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1GetProjectPgbouncerConfigRequest$ {
  /** @deprecated use `V1GetProjectPgbouncerConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V1GetProjectPgbouncerConfigRequest$inboundSchema;
  /** @deprecated use `V1GetProjectPgbouncerConfigRequest$outboundSchema` instead. */
  export const outboundSchema =
    V1GetProjectPgbouncerConfigRequest$outboundSchema;
  /** @deprecated use `V1GetProjectPgbouncerConfigRequest$Outbound` instead. */
  export type Outbound = V1GetProjectPgbouncerConfigRequest$Outbound;
}

export function v1GetProjectPgbouncerConfigRequestToJSON(
  v1GetProjectPgbouncerConfigRequest: V1GetProjectPgbouncerConfigRequest,
): string {
  return JSON.stringify(
    V1GetProjectPgbouncerConfigRequest$outboundSchema.parse(
      v1GetProjectPgbouncerConfigRequest,
    ),
  );
}

export function v1GetProjectPgbouncerConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1GetProjectPgbouncerConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1GetProjectPgbouncerConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1GetProjectPgbouncerConfigRequest' from JSON`,
  );
}
