/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1GetAFunctionBodyRequest = {
  /**
   * Project ref
   */
  ref: string;
  /**
   * Function slug
   */
  slug: string;
};

/** @internal */
export const V1GetAFunctionBodyRequest$inboundSchema: z.ZodType<
  V1GetAFunctionBodyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  slug: z.string(),
});

/** @internal */
export type V1GetAFunctionBodyRequest$Outbound = {
  ref: string;
  slug: string;
};

/** @internal */
export const V1GetAFunctionBodyRequest$outboundSchema: z.ZodType<
  V1GetAFunctionBodyRequest$Outbound,
  z.ZodTypeDef,
  V1GetAFunctionBodyRequest
> = z.object({
  ref: z.string(),
  slug: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1GetAFunctionBodyRequest$ {
  /** @deprecated use `V1GetAFunctionBodyRequest$inboundSchema` instead. */
  export const inboundSchema = V1GetAFunctionBodyRequest$inboundSchema;
  /** @deprecated use `V1GetAFunctionBodyRequest$outboundSchema` instead. */
  export const outboundSchema = V1GetAFunctionBodyRequest$outboundSchema;
  /** @deprecated use `V1GetAFunctionBodyRequest$Outbound` instead. */
  export type Outbound = V1GetAFunctionBodyRequest$Outbound;
}

export function v1GetAFunctionBodyRequestToJSON(
  v1GetAFunctionBodyRequest: V1GetAFunctionBodyRequest,
): string {
  return JSON.stringify(
    V1GetAFunctionBodyRequest$outboundSchema.parse(v1GetAFunctionBodyRequest),
  );
}

export function v1GetAFunctionBodyRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1GetAFunctionBodyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1GetAFunctionBodyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1GetAFunctionBodyRequest' from JSON`,
  );
}
