/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1ListAllFunctionsRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1ListAllFunctionsRequest$inboundSchema: z.ZodType<
  V1ListAllFunctionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1ListAllFunctionsRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1ListAllFunctionsRequest$outboundSchema: z.ZodType<
  V1ListAllFunctionsRequest$Outbound,
  z.ZodTypeDef,
  V1ListAllFunctionsRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1ListAllFunctionsRequest$ {
  /** @deprecated use `V1ListAllFunctionsRequest$inboundSchema` instead. */
  export const inboundSchema = V1ListAllFunctionsRequest$inboundSchema;
  /** @deprecated use `V1ListAllFunctionsRequest$outboundSchema` instead. */
  export const outboundSchema = V1ListAllFunctionsRequest$outboundSchema;
  /** @deprecated use `V1ListAllFunctionsRequest$Outbound` instead. */
  export type Outbound = V1ListAllFunctionsRequest$Outbound;
}

export function v1ListAllFunctionsRequestToJSON(
  v1ListAllFunctionsRequest: V1ListAllFunctionsRequest,
): string {
  return JSON.stringify(
    V1ListAllFunctionsRequest$outboundSchema.parse(v1ListAllFunctionsRequest),
  );
}

export function v1ListAllFunctionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1ListAllFunctionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1ListAllFunctionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1ListAllFunctionsRequest' from JSON`,
  );
}
