/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1ListAllSsoProviderRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1ListAllSsoProviderRequest$inboundSchema: z.ZodType<
  V1ListAllSsoProviderRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1ListAllSsoProviderRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1ListAllSsoProviderRequest$outboundSchema: z.ZodType<
  V1ListAllSsoProviderRequest$Outbound,
  z.ZodTypeDef,
  V1ListAllSsoProviderRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1ListAllSsoProviderRequest$ {
  /** @deprecated use `V1ListAllSsoProviderRequest$inboundSchema` instead. */
  export const inboundSchema = V1ListAllSsoProviderRequest$inboundSchema;
  /** @deprecated use `V1ListAllSsoProviderRequest$outboundSchema` instead. */
  export const outboundSchema = V1ListAllSsoProviderRequest$outboundSchema;
  /** @deprecated use `V1ListAllSsoProviderRequest$Outbound` instead. */
  export type Outbound = V1ListAllSsoProviderRequest$Outbound;
}

export function v1ListAllSsoProviderRequestToJSON(
  v1ListAllSsoProviderRequest: V1ListAllSsoProviderRequest,
): string {
  return JSON.stringify(
    V1ListAllSsoProviderRequest$outboundSchema.parse(
      v1ListAllSsoProviderRequest,
    ),
  );
}

export function v1ListAllSsoProviderRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1ListAllSsoProviderRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1ListAllSsoProviderRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1ListAllSsoProviderRequest' from JSON`,
  );
}
