/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1ListAllBranchesRequest = {
  /**
   * Project ref
   */
  ref: string;
};

/** @internal */
export const V1ListAllBranchesRequest$inboundSchema: z.ZodType<
  V1ListAllBranchesRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
});

/** @internal */
export type V1ListAllBranchesRequest$Outbound = {
  ref: string;
};

/** @internal */
export const V1ListAllBranchesRequest$outboundSchema: z.ZodType<
  V1ListAllBranchesRequest$Outbound,
  z.ZodTypeDef,
  V1ListAllBranchesRequest
> = z.object({
  ref: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1ListAllBranchesRequest$ {
  /** @deprecated use `V1ListAllBranchesRequest$inboundSchema` instead. */
  export const inboundSchema = V1ListAllBranchesRequest$inboundSchema;
  /** @deprecated use `V1ListAllBranchesRequest$outboundSchema` instead. */
  export const outboundSchema = V1ListAllBranchesRequest$outboundSchema;
  /** @deprecated use `V1ListAllBranchesRequest$Outbound` instead. */
  export type Outbound = V1ListAllBranchesRequest$Outbound;
}

export function v1ListAllBranchesRequestToJSON(
  v1ListAllBranchesRequest: V1ListAllBranchesRequest,
): string {
  return JSON.stringify(
    V1ListAllBranchesRequest$outboundSchema.parse(v1ListAllBranchesRequest),
  );
}

export function v1ListAllBranchesRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1ListAllBranchesRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1ListAllBranchesRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1ListAllBranchesRequest' from JSON`,
  );
}
