/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1UpdateNetworkRestrictionsRequest = {
  /**
   * Project ref
   */
  ref: string;
  networkRestrictionsRequest: components.NetworkRestrictionsRequest;
};

/** @internal */
export const V1UpdateNetworkRestrictionsRequest$inboundSchema: z.ZodType<
  V1UpdateNetworkRestrictionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  NetworkRestrictionsRequest:
    components.NetworkRestrictionsRequest$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "NetworkRestrictionsRequest": "networkRestrictionsRequest",
  });
});

/** @internal */
export type V1UpdateNetworkRestrictionsRequest$Outbound = {
  ref: string;
  NetworkRestrictionsRequest: components.NetworkRestrictionsRequest$Outbound;
};

/** @internal */
export const V1UpdateNetworkRestrictionsRequest$outboundSchema: z.ZodType<
  V1UpdateNetworkRestrictionsRequest$Outbound,
  z.ZodTypeDef,
  V1UpdateNetworkRestrictionsRequest
> = z.object({
  ref: z.string(),
  networkRestrictionsRequest:
    components.NetworkRestrictionsRequest$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    networkRestrictionsRequest: "NetworkRestrictionsRequest",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdateNetworkRestrictionsRequest$ {
  /** @deprecated use `V1UpdateNetworkRestrictionsRequest$inboundSchema` instead. */
  export const inboundSchema = V1UpdateNetworkRestrictionsRequest$inboundSchema;
  /** @deprecated use `V1UpdateNetworkRestrictionsRequest$outboundSchema` instead. */
  export const outboundSchema =
    V1UpdateNetworkRestrictionsRequest$outboundSchema;
  /** @deprecated use `V1UpdateNetworkRestrictionsRequest$Outbound` instead. */
  export type Outbound = V1UpdateNetworkRestrictionsRequest$Outbound;
}

export function v1UpdateNetworkRestrictionsRequestToJSON(
  v1UpdateNetworkRestrictionsRequest: V1UpdateNetworkRestrictionsRequest,
): string {
  return JSON.stringify(
    V1UpdateNetworkRestrictionsRequest$outboundSchema.parse(
      v1UpdateNetworkRestrictionsRequest,
    ),
  );
}

export function v1UpdateNetworkRestrictionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1UpdateNetworkRestrictionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      V1UpdateNetworkRestrictionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1UpdateNetworkRestrictionsRequest' from JSON`,
  );
}
