/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1UpdatePostgresConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
  updatePostgresConfigBody: components.UpdatePostgresConfigBody;
};

/** @internal */
export const V1UpdatePostgresConfigRequest$inboundSchema: z.ZodType<
  V1UpdatePostgresConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  UpdatePostgresConfigBody: components.UpdatePostgresConfigBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdatePostgresConfigBody": "updatePostgresConfigBody",
  });
});

/** @internal */
export type V1UpdatePostgresConfigRequest$Outbound = {
  ref: string;
  UpdatePostgresConfigBody: components.UpdatePostgresConfigBody$Outbound;
};

/** @internal */
export const V1UpdatePostgresConfigRequest$outboundSchema: z.ZodType<
  V1UpdatePostgresConfigRequest$Outbound,
  z.ZodTypeDef,
  V1UpdatePostgresConfigRequest
> = z.object({
  ref: z.string(),
  updatePostgresConfigBody: components.UpdatePostgresConfigBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updatePostgresConfigBody: "UpdatePostgresConfigBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdatePostgresConfigRequest$ {
  /** @deprecated use `V1UpdatePostgresConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V1UpdatePostgresConfigRequest$inboundSchema;
  /** @deprecated use `V1UpdatePostgresConfigRequest$outboundSchema` instead. */
  export const outboundSchema = V1UpdatePostgresConfigRequest$outboundSchema;
  /** @deprecated use `V1UpdatePostgresConfigRequest$Outbound` instead. */
  export type Outbound = V1UpdatePostgresConfigRequest$Outbound;
}

export function v1UpdatePostgresConfigRequestToJSON(
  v1UpdatePostgresConfigRequest: V1UpdatePostgresConfigRequest,
): string {
  return JSON.stringify(
    V1UpdatePostgresConfigRequest$outboundSchema.parse(
      v1UpdatePostgresConfigRequest,
    ),
  );
}

export function v1UpdatePostgresConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1UpdatePostgresConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1UpdatePostgresConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1UpdatePostgresConfigRequest' from JSON`,
  );
}
