/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1UpdatePgsodiumConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
  updatePgsodiumConfigBody: components.UpdatePgsodiumConfigBody;
};

/** @internal */
export const V1UpdatePgsodiumConfigRequest$inboundSchema: z.ZodType<
  V1UpdatePgsodiumConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  UpdatePgsodiumConfigBody: components.UpdatePgsodiumConfigBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdatePgsodiumConfigBody": "updatePgsodiumConfigBody",
  });
});

/** @internal */
export type V1UpdatePgsodiumConfigRequest$Outbound = {
  ref: string;
  UpdatePgsodiumConfigBody: components.UpdatePgsodiumConfigBody$Outbound;
};

/** @internal */
export const V1UpdatePgsodiumConfigRequest$outboundSchema: z.ZodType<
  V1UpdatePgsodiumConfigRequest$Outbound,
  z.ZodTypeDef,
  V1UpdatePgsodiumConfigRequest
> = z.object({
  ref: z.string(),
  updatePgsodiumConfigBody: components.UpdatePgsodiumConfigBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updatePgsodiumConfigBody: "UpdatePgsodiumConfigBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdatePgsodiumConfigRequest$ {
  /** @deprecated use `V1UpdatePgsodiumConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V1UpdatePgsodiumConfigRequest$inboundSchema;
  /** @deprecated use `V1UpdatePgsodiumConfigRequest$outboundSchema` instead. */
  export const outboundSchema = V1UpdatePgsodiumConfigRequest$outboundSchema;
  /** @deprecated use `V1UpdatePgsodiumConfigRequest$Outbound` instead. */
  export type Outbound = V1UpdatePgsodiumConfigRequest$Outbound;
}

export function v1UpdatePgsodiumConfigRequestToJSON(
  v1UpdatePgsodiumConfigRequest: V1UpdatePgsodiumConfigRequest,
): string {
  return JSON.stringify(
    V1UpdatePgsodiumConfigRequest$outboundSchema.parse(
      v1UpdatePgsodiumConfigRequest,
    ),
  );
}

export function v1UpdatePgsodiumConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1UpdatePgsodiumConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1UpdatePgsodiumConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1UpdatePgsodiumConfigRequest' from JSON`,
  );
}
