/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1UpdateAuthServiceConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
  updateAuthConfigBody: components.UpdateAuthConfigBody;
};

/** @internal */
export const V1UpdateAuthServiceConfigRequest$inboundSchema: z.ZodType<
  V1UpdateAuthServiceConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  UpdateAuthConfigBody: components.UpdateAuthConfigBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateAuthConfigBody": "updateAuthConfigBody",
  });
});

/** @internal */
export type V1UpdateAuthServiceConfigRequest$Outbound = {
  ref: string;
  UpdateAuthConfigBody: components.UpdateAuthConfigBody$Outbound;
};

/** @internal */
export const V1UpdateAuthServiceConfigRequest$outboundSchema: z.ZodType<
  V1UpdateAuthServiceConfigRequest$Outbound,
  z.ZodTypeDef,
  V1UpdateAuthServiceConfigRequest
> = z.object({
  ref: z.string(),
  updateAuthConfigBody: components.UpdateAuthConfigBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateAuthConfigBody: "UpdateAuthConfigBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdateAuthServiceConfigRequest$ {
  /** @deprecated use `V1UpdateAuthServiceConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V1UpdateAuthServiceConfigRequest$inboundSchema;
  /** @deprecated use `V1UpdateAuthServiceConfigRequest$outboundSchema` instead. */
  export const outboundSchema = V1UpdateAuthServiceConfigRequest$outboundSchema;
  /** @deprecated use `V1UpdateAuthServiceConfigRequest$Outbound` instead. */
  export type Outbound = V1UpdateAuthServiceConfigRequest$Outbound;
}

export function v1UpdateAuthServiceConfigRequestToJSON(
  v1UpdateAuthServiceConfigRequest: V1UpdateAuthServiceConfigRequest,
): string {
  return JSON.stringify(
    V1UpdateAuthServiceConfigRequest$outboundSchema.parse(
      v1UpdateAuthServiceConfigRequest,
    ),
  );
}

export function v1UpdateAuthServiceConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1UpdateAuthServiceConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1UpdateAuthServiceConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1UpdateAuthServiceConfigRequest' from JSON`,
  );
}
