/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type V1UpdateSupavisorConfigRequest = {
  /**
   * Project ref
   */
  ref: string;
  updateSupavisorConfigBody: components.UpdateSupavisorConfigBody;
};

/** @internal */
export const V1UpdateSupavisorConfigRequest$inboundSchema: z.ZodType<
  V1UpdateSupavisorConfigRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  ref: z.string(),
  UpdateSupavisorConfigBody: components.UpdateSupavisorConfigBody$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "UpdateSupavisorConfigBody": "updateSupavisorConfigBody",
  });
});

/** @internal */
export type V1UpdateSupavisorConfigRequest$Outbound = {
  ref: string;
  UpdateSupavisorConfigBody: components.UpdateSupavisorConfigBody$Outbound;
};

/** @internal */
export const V1UpdateSupavisorConfigRequest$outboundSchema: z.ZodType<
  V1UpdateSupavisorConfigRequest$Outbound,
  z.ZodTypeDef,
  V1UpdateSupavisorConfigRequest
> = z.object({
  ref: z.string(),
  updateSupavisorConfigBody:
    components.UpdateSupavisorConfigBody$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    updateSupavisorConfigBody: "UpdateSupavisorConfigBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace V1UpdateSupavisorConfigRequest$ {
  /** @deprecated use `V1UpdateSupavisorConfigRequest$inboundSchema` instead. */
  export const inboundSchema = V1UpdateSupavisorConfigRequest$inboundSchema;
  /** @deprecated use `V1UpdateSupavisorConfigRequest$outboundSchema` instead. */
  export const outboundSchema = V1UpdateSupavisorConfigRequest$outboundSchema;
  /** @deprecated use `V1UpdateSupavisorConfigRequest$Outbound` instead. */
  export type Outbound = V1UpdateSupavisorConfigRequest$Outbound;
}

export function v1UpdateSupavisorConfigRequestToJSON(
  v1UpdateSupavisorConfigRequest: V1UpdateSupavisorConfigRequest,
): string {
  return JSON.stringify(
    V1UpdateSupavisorConfigRequest$outboundSchema.parse(
      v1UpdateSupavisorConfigRequest,
    ),
  );
}

export function v1UpdateSupavisorConfigRequestFromJSON(
  jsonString: string,
): SafeParseResult<V1UpdateSupavisorConfigRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => V1UpdateSupavisorConfigRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'V1UpdateSupavisorConfigRequest' from JSON`,
  );
}
