/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const BillingPlanId = {
  Free: "free",
  Pro: "pro",
  Team: "team",
  Enterprise: "enterprise",
} as const;
export type BillingPlanId = ClosedEnum<typeof BillingPlanId>;

/** @internal */
export const BillingPlanId$inboundSchema: z.ZodNativeEnum<
  typeof BillingPlanId
> = z.nativeEnum(BillingPlanId);

/** @internal */
export const BillingPlanId$outboundSchema: z.ZodNativeEnum<
  typeof BillingPlanId
> = BillingPlanId$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BillingPlanId$ {
  /** @deprecated use `BillingPlanId$inboundSchema` instead. */
  export const inboundSchema = BillingPlanId$inboundSchema;
  /** @deprecated use `BillingPlanId$outboundSchema` instead. */
  export const outboundSchema = BillingPlanId$outboundSchema;
}
