/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type NetworkBanResponse = {
  bannedIpv4Addresses: Array<string>;
};

/** @internal */
export const NetworkBanResponse$inboundSchema: z.ZodType<
  NetworkBanResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  banned_ipv4_addresses: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    "banned_ipv4_addresses": "bannedIpv4Addresses",
  });
});

/** @internal */
export type NetworkBanResponse$Outbound = {
  banned_ipv4_addresses: Array<string>;
};

/** @internal */
export const NetworkBanResponse$outboundSchema: z.ZodType<
  NetworkBanResponse$Outbound,
  z.ZodTypeDef,
  NetworkBanResponse
> = z.object({
  bannedIpv4Addresses: z.array(z.string()),
}).transform((v) => {
  return remap$(v, {
    bannedIpv4Addresses: "banned_ipv4_addresses",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace NetworkBanResponse$ {
  /** @deprecated use `NetworkBanResponse$inboundSchema` instead. */
  export const inboundSchema = NetworkBanResponse$inboundSchema;
  /** @deprecated use `NetworkBanResponse$outboundSchema` instead. */
  export const outboundSchema = NetworkBanResponse$outboundSchema;
  /** @deprecated use `NetworkBanResponse$Outbound` instead. */
  export type Outbound = NetworkBanResponse$Outbound;
}

export function networkBanResponseToJSON(
  networkBanResponse: NetworkBanResponse,
): string {
  return JSON.stringify(
    NetworkBanResponse$outboundSchema.parse(networkBanResponse),
  );
}

export function networkBanResponseFromJSON(
  jsonString: string,
): SafeParseResult<NetworkBanResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => NetworkBanResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'NetworkBanResponse' from JSON`,
  );
}
