/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ProjectUpgradeInitiateResponse = {
  trackingId: string;
};

/** @internal */
export const ProjectUpgradeInitiateResponse$inboundSchema: z.ZodType<
  ProjectUpgradeInitiateResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  tracking_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "tracking_id": "trackingId",
  });
});

/** @internal */
export type ProjectUpgradeInitiateResponse$Outbound = {
  tracking_id: string;
};

/** @internal */
export const ProjectUpgradeInitiateResponse$outboundSchema: z.ZodType<
  ProjectUpgradeInitiateResponse$Outbound,
  z.ZodTypeDef,
  ProjectUpgradeInitiateResponse
> = z.object({
  trackingId: z.string(),
}).transform((v) => {
  return remap$(v, {
    trackingId: "tracking_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ProjectUpgradeInitiateResponse$ {
  /** @deprecated use `ProjectUpgradeInitiateResponse$inboundSchema` instead. */
  export const inboundSchema = ProjectUpgradeInitiateResponse$inboundSchema;
  /** @deprecated use `ProjectUpgradeInitiateResponse$outboundSchema` instead. */
  export const outboundSchema = ProjectUpgradeInitiateResponse$outboundSchema;
  /** @deprecated use `ProjectUpgradeInitiateResponse$Outbound` instead. */
  export type Outbound = ProjectUpgradeInitiateResponse$Outbound;
}

export function projectUpgradeInitiateResponseToJSON(
  projectUpgradeInitiateResponse: ProjectUpgradeInitiateResponse,
): string {
  return JSON.stringify(
    ProjectUpgradeInitiateResponse$outboundSchema.parse(
      projectUpgradeInitiateResponse,
    ),
  );
}

export function projectUpgradeInitiateResponseFromJSON(
  jsonString: string,
): SafeParseResult<ProjectUpgradeInitiateResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProjectUpgradeInitiateResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProjectUpgradeInitiateResponse' from JSON`,
  );
}
