/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const ReleaseChannel = {
  Internal: "internal",
  Alpha: "alpha",
  Beta: "beta",
  Ga: "ga",
  Withdrawn: "withdrawn",
} as const;
export type ReleaseChannel = ClosedEnum<typeof ReleaseChannel>;

/** @internal */
export const ReleaseChannel$inboundSchema: z.ZodNativeEnum<
  typeof ReleaseChannel
> = z.nativeEnum(ReleaseChannel);

/** @internal */
export const ReleaseChannel$outboundSchema: z.ZodNativeEnum<
  typeof ReleaseChannel
> = ReleaseChannel$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ReleaseChannel$ {
  /** @deprecated use `ReleaseChannel$inboundSchema` instead. */
  export const inboundSchema = ReleaseChannel$inboundSchema;
  /** @deprecated use `ReleaseChannel$outboundSchema` instead. */
  export const outboundSchema = ReleaseChannel$outboundSchema;
}
