/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type SubdomainAvailabilityResponse = {
  available: boolean;
};

/** @internal */
export const SubdomainAvailabilityResponse$inboundSchema: z.ZodType<
  SubdomainAvailabilityResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  available: z.boolean(),
});

/** @internal */
export type SubdomainAvailabilityResponse$Outbound = {
  available: boolean;
};

/** @internal */
export const SubdomainAvailabilityResponse$outboundSchema: z.ZodType<
  SubdomainAvailabilityResponse$Outbound,
  z.ZodTypeDef,
  SubdomainAvailabilityResponse
> = z.object({
  available: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace SubdomainAvailabilityResponse$ {
  /** @deprecated use `SubdomainAvailabilityResponse$inboundSchema` instead. */
  export const inboundSchema = SubdomainAvailabilityResponse$inboundSchema;
  /** @deprecated use `SubdomainAvailabilityResponse$outboundSchema` instead. */
  export const outboundSchema = SubdomainAvailabilityResponse$outboundSchema;
  /** @deprecated use `SubdomainAvailabilityResponse$Outbound` instead. */
  export type Outbound = SubdomainAvailabilityResponse$Outbound;
}

export function subdomainAvailabilityResponseToJSON(
  subdomainAvailabilityResponse: SubdomainAvailabilityResponse,
): string {
  return JSON.stringify(
    SubdomainAvailabilityResponse$outboundSchema.parse(
      subdomainAvailabilityResponse,
    ),
  );
}

export function subdomainAvailabilityResponseFromJSON(
  jsonString: string,
): SafeParseResult<SubdomainAvailabilityResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SubdomainAvailabilityResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SubdomainAvailabilityResponse' from JSON`,
  );
}
