workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    supabase-provider:
        inputs:
            - location: ./beta.yaml
        overlays:
            - location: ./transformations.yaml
            - location: ./beta_errors.yaml
        output: output.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-onboarding/onboarding/supabase-provider
targets:
    supabase:
        target: terraform
        source: supabase-provider
    supabase-ts:
        target: typescript
        source: supabase-provider
        output: ./speakeasy-ts
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-onboarding/onboarding/supabase-provider-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
