// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/speakeasy/terraform-provider-supabase/internal/provider/types"
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk"
	"github.com/speakeasy/terraform-provider-supabase/internal/sdk/models/operations"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &PoolerDataSource{}
var _ datasource.DataSourceWithConfigure = &PoolerDataSource{}

func NewPoolerDataSource() datasource.DataSource {
	return &PoolerDataSource{}
}

// PoolerDataSource is the data source implementation.
type PoolerDataSource struct {
	client *sdk.Supabase
}

// PoolerDataSourceModel describes the data model.
type PoolerDataSourceModel struct {
	Data []tfTypes.SupavisorConfigResponse `tfsdk:"data"`
	Ref  types.String                      `tfsdk:"ref"`
}

// Metadata returns the data source type name.
func (r *PoolerDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_pooler"
}

// Schema defines the schema for the data source.
func (r *PoolerDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Pooler DataSource",

		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"connection_string": schema.StringAttribute{
							Computed: true,
						},
						"database_type": schema.StringAttribute{
							Computed: true,
						},
						"db_host": schema.StringAttribute{
							Computed: true,
						},
						"db_name": schema.StringAttribute{
							Computed: true,
						},
						"db_port": schema.Int64Attribute{
							Computed: true,
						},
						"db_user": schema.StringAttribute{
							Computed: true,
						},
						"default_pool_size": schema.Int64Attribute{
							Computed: true,
						},
						"identifier": schema.StringAttribute{
							Computed: true,
						},
						"is_using_scram_auth": schema.BoolAttribute{
							Computed: true,
						},
						"max_client_conn": schema.Int64Attribute{
							Computed: true,
						},
						"pool_mode": schema.StringAttribute{
							Computed: true,
						},
					},
				},
			},
			"ref": schema.StringAttribute{
				Required:    true,
				Description: `Project ref`,
			},
		},
	}
}

func (r *PoolerDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.Supabase)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.Supabase, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *PoolerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *PoolerDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	var ref string
	ref = data.Ref.ValueString()

	request := operations.V1GetSupavisorConfigRequest{
		Ref: ref,
	}
	res, err := r.client.Database.GetSupavisorConfig(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.SupavisorConfigResponses != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromSharedSupavisorConfigResponse(res.SupavisorConfigResponses)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
