// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"supabase/internal/sdk/pkg/models/shared"
)

func (r *ProjectResourceModel) ToCreateSDKType() *shared.CreateProjectBody {
	dbPass := r.DbPass.ValueString()
	kpsEnabled := new(bool)
	if !r.KpsEnabled.IsUnknown() && !r.KpsEnabled.IsNull() {
		*kpsEnabled = r.KpsEnabled.ValueBool()
	} else {
		kpsEnabled = nil
	}
	name := r.Name.ValueString()
	organizationID := r.OrganizationID.ValueString()
	plan := shared.CreateProjectBodyPlanEnum(r.Plan.ValueString())
	region := shared.CreateProjectBodyRegionEnum(r.Region.ValueString())
	out := shared.CreateProjectBody{
		DbPass:         dbPass,
		KpsEnabled:     kpsEnabled,
		Name:           name,
		OrganizationID: organizationID,
		Plan:           plan,
		Region:         region,
	}
	return &out
}

func (r *ProjectResourceModel) RefreshFromCreateResponse(resp *shared.ProjectResponse) {
	r.CreatedAt = types.StringValue(resp.CreatedAt)
	if resp.Database == nil {
		r.Database = nil
	} else {
		r.Database = &DatabaseResponse{}
		r.Database.Host = types.StringValue(resp.Database.Host)
		r.Database.Version = types.StringValue(resp.Database.Version)
	}
	r.ID = types.StringValue(resp.ID)
	r.Name = types.StringValue(resp.Name)
	r.OrganizationID = types.StringValue(resp.OrganizationID)
	r.Region = types.StringValue(resp.Region)
}
