/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Auth } from "./auth.js";
import { Database } from "./database.js";
import { Databases } from "./databases.js";
import { Domains } from "./domains.js";
import { EdgeFunctions } from "./edgefunctions.js";
import { Environments } from "./environments.js";
import { Oauth } from "./oauth.js";
import { Organizations } from "./organizations.js";
import { Projects } from "./projects.js";
import { Rest } from "./rest.js";
import { Secrets } from "./secrets.js";
import { Snippets } from "./snippets.js";
import { Storage } from "./storage.js";

export class Supabase extends ClientSDK {
  private _environments?: Environments;
  get environments(): Environments {
    return (this._environments ??= new Environments(this._options));
  }

  private _projects?: Projects;
  get projects(): Projects {
    return (this._projects ??= new Projects(this._options));
  }

  private _organizations?: Organizations;
  get organizations(): Organizations {
    return (this._organizations ??= new Organizations(this._options));
  }

  private _oauth?: Oauth;
  get oauth(): Oauth {
    return (this._oauth ??= new Oauth(this._options));
  }

  private _snippets?: Snippets;
  get snippets(): Snippets {
    return (this._snippets ??= new Snippets(this._options));
  }

  private _database?: Database;
  get database(): Database {
    return (this._database ??= new Database(this._options));
  }

  private _secrets?: Secrets;
  get secrets(): Secrets {
    return (this._secrets ??= new Secrets(this._options));
  }

  private _domains?: Domains;
  get domains(): Domains {
    return (this._domains ??= new Domains(this._options));
  }

  private _rest?: Rest;
  get rest(): Rest {
    return (this._rest ??= new Rest(this._options));
  }

  private _databases?: Databases;
  get databases(): Databases {
    return (this._databases ??= new Databases(this._options));
  }

  private _storage?: Storage;
  get storage(): Storage {
    return (this._storage ??= new Storage(this._options));
  }

  private _auth?: Auth;
  get auth(): Auth {
    return (this._auth ??= new Auth(this._options));
  }

  private _edgeFunctions?: EdgeFunctions;
  get edgeFunctions(): EdgeFunctions {
    return (this._edgeFunctions ??= new EdgeFunctions(this._options));
  }
}
