// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type SupavisorConfigResponse struct {
	ConnectionString types.String `tfsdk:"connection_string"`
	DatabaseType     types.String `tfsdk:"database_type"`
	DbHost           types.String `tfsdk:"db_host"`
	DbName           types.String `tfsdk:"db_name"`
	DbPort           types.Int64  `tfsdk:"db_port"`
	DbUser           types.String `tfsdk:"db_user"`
	DefaultPoolSize  types.Int64  `tfsdk:"default_pool_size"`
	Identifier       types.String `tfsdk:"identifier"`
	IsUsingScramAuth types.Bool   `tfsdk:"is_using_scram_auth"`
	MaxClientConn    types.Int64  `tfsdk:"max_client_conn"`
	PoolMode         types.String `tfsdk:"pool_mode"`
}
