// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type V1DatabaseResponse struct {
	Host           types.String `tfsdk:"host"`
	PostgresEngine types.String `tfsdk:"postgres_engine"`
	ReleaseChannel types.String `tfsdk:"release_channel"`
	Version        types.String `tfsdk:"version"`
}
