// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type ActivateVanitySubdomainPleaseRequest struct {
	VanitySubdomainBody shared.VanitySubdomainBody `request:"mediaType=application/json"`
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type ActivateVanitySubdomainPleaseResponse struct {
	ActivateVanitySubdomainResponse *shared.ActivateVanitySubdomainResponse
	ContentType                     string
	StatusCode                      int
	RawResponse                     *http.Response
}
