// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type ApplyNetworkRestrictionsRequest struct {
	NetworkRestrictionsRequest shared.NetworkRestrictionsRequest `request:"mediaType=application/json"`
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type ApplyNetworkRestrictionsResponse struct {
	ContentType                 string
	NetworkRestrictionsResponse *shared.NetworkRestrictionsResponse
	StatusCode                  int
	RawResponse                 *http.Response
}
