// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type CreateOrganizationResponse struct {
	ContentType          string
	OrganizationResponse *shared.OrganizationResponse
	StatusCode           int
	RawResponse          *http.Response
}
