// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type GetFunctionBodyRequest struct {
	// Function slug
	FunctionSlug string `pathParam:"style=simple,explode=false,name=function_slug"`
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type GetFunctionBodyResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
}
