// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type GetNetworkBansRequest struct {
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type GetNetworkBansResponse struct {
	ContentType        string
	NetworkBanResponse *shared.NetworkBanResponse
	StatusCode         int
	RawResponse        *http.Response
}
