// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type GetOrganizationsResponse struct {
	ContentType           string
	OrganizationResponses []shared.OrganizationResponse
	StatusCode            int
	RawResponse           *http.Response
}
