// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type GetPGSodiumConfigRequest struct {
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type GetPGSodiumConfigResponse struct {
	ContentType            string
	PgsodiumConfigResponse *shared.PgsodiumConfigResponse
	StatusCode             int
	RawResponse            *http.Response
}
