// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type GetReadOnlyModeStatusRequest struct {
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type GetReadOnlyModeStatusResponse struct {
	ContentType            string
	ReadOnlyStatusResponse *shared.ReadOnlyStatusResponse
	StatusCode             int
	RawResponse            *http.Response
}
