// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type ListAllProvidersRequest struct {
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type ListAllProvidersResponse struct {
	ContentType           string
	ListProvidersResponse *shared.ListProvidersResponse
	StatusCode            int
	RawResponse           *http.Response
}
