// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type RemoveProviderByIDRequest struct {
	ProviderID string `pathParam:"style=simple,explode=false,name=provider_id"`
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type RemoveProviderByIDResponse struct {
	ContentType            string
	DeleteProviderResponse *shared.DeleteProviderResponse
	StatusCode             int
	RawResponse            *http.Response
}
