// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type UpdateProviderByIDRequest struct {
	UpdateProviderBody shared.UpdateProviderBody `request:"mediaType=application/json"`
	ProviderID         string                    `pathParam:"style=simple,explode=false,name=provider_id"`
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type UpdateProviderByIDResponse struct {
	ContentType            string
	StatusCode             int
	RawResponse            *http.Response
	UpdateProviderResponse *shared.UpdateProviderResponse
}
