// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supabase/internal/sdk/pkg/models/shared"
)

type UpdatePostgresConfigRequest struct {
	UpdatePostgresConfigBody shared.UpdatePostgresConfigBody `request:"mediaType=application/json"`
	// Project ref
	Ref string `pathParam:"style=simple,explode=false,name=ref"`
}

type UpdatePostgresConfigResponse struct {
	ContentType            string
	PostgresConfigResponse *shared.PostgresConfigResponse
	StatusCode             int
	RawResponse            *http.Response
}
